### ISSUE TITLE
Improve shortcode

### ISSUE THREAD

**Issue by khromov** [pelmered/ShareBird#15]
* Remove test code
* Add support for specifying template
* Add support for passing a post ID as a parameter
* enable/disable parameters are not used, remove

**Comment by khromov** [comment]
Should be all fixed no! @pelmered

**Comment by pelmered** [comment]
Yes, I agree. I had a local branch where I worked on this, but I'm not sure I still have it unfortunately since I have a new computer.
I will look into this tonight.

**Comment by pelmered** [comment]
Yes, I think so too.
