### ISSUE TITLE
Remove The Loop dependency

### ISSUE THREAD

**Issue by khromov** [pelmered/ShareBird#4]
Some functions still rely on The Loop being set up to work, which means this will not work with custom loops. Refactor to take the post / author id as a parameter (both in output_buttons() and in the shortcode) and default to using the global variables if nothing else is set.

**Comment by khromov** [comment]
Partially fixed in @b3dea2d

**Comment by pelmered** [comment]
I have tested this with several different custom loops so I think this is fixed with my last commit.
